### ISSUE TITLE
Separate video backend

### ISSUE THREAD

**Issue by ApolloLV** [ApolloLV/flunkysimulator#64] opened 2020-05-06 17:47 UTC
We currently rebase a local commit onto master and push that to Heroku for a release.
This obviously does not scale well and uploading 180MB for every release, building a Heroku image etc. takes more time than necessary.
Additionally, this prevents continuous integration, since we don't want to put those videos into a public GitHub repo.
We could just split the videos into its own repository that is then deployed to a second Heroku instance that does not need updating when the code changes. This can then be migrated more easily to a different hosting solution (See #32 for suggestions).

**Comment by stheid** [comment] 2020-05-07 17:36
potzential duplicate of #9

**Closed** 2020-05-16 19:13 UTC
Labels: Client, enhancement
