### ISSUE TITLE
[serverKotlin] Strip all weird characters from usernames

### ISSUE THREAD

**Issue by ApolloLV** [ApolloLV/flunkysimulator#40] opened 2020-04-29 07:41 UTC
This also requires the server telling the clientJS in the response to the register request what his stripped playerName is.
We need to strip all whitespace at beginning and end and escape everything that has special meaning in HTML. 
See https://stackoverflow.com/questions/1265282/recommended-method-for-escaping-html-in-java for ways to do it in Java.

**Comment by moreApi** [comment] 2020-05-01 18:16
Duplicate of #26

**Closed by moreApi** 2020-05-01 18:16 UTC
Labels: Server
